// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh2rb3dTJ_d6zLLvK1YiTY8129ZC8Wxp4',
    appId: '1:260724624293:web:e4b976b7c4f1a6814b364c',
    messagingSenderId: '260724624293',
    projectId: 'flutter-chatapp-d70e7',
    authDomain: 'flutter-chatapp-d70e7.firebaseapp.com',
    storageBucket: 'flutter-chatapp-d70e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA--8ijQHGr5Rv1xAGz-WzpA53FJ6B1U9A',
    appId: '1:260724624293:android:005dc194d84171264b364c',
    messagingSenderId: '260724624293',
    projectId: 'flutter-chatapp-d70e7',
    storageBucket: 'flutter-chatapp-d70e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEmFM8H0pSmwBVvZuZ7GWh6QBgcRRI5Ag',
    appId: '1:260724624293:ios:62294837f27d033f4b364c',
    messagingSenderId: '260724624293',
    projectId: 'flutter-chatapp-d70e7',
    storageBucket: 'flutter-chatapp-d70e7.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
